-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bitacora (
  id bigint NOT NULL DEFAULT nextval('bitacora_id_seq'::regclass),
  obra_id bigint NOT NULL,
  fecha timestamp with time zone DEFAULT now(),
  titulo text NOT NULL,
  descripcion text NOT NULL,
  clima text CHECK (clima = ANY (ARRAY['soleado'::text, 'nublado'::text, 'lluvia'::text, 'viento'::text])),
  temperatura numeric,
  trabajadores_presentes integer,
  fotos ARRAY,
  autor_id bigint,
  CONSTRAINT bitacora_pkey PRIMARY KEY (id),
  CONSTRAINT bitacora_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id),
  CONSTRAINT bitacora_autor_id_fkey FOREIGN KEY (autor_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.configuracion_empresa (
  id bigint NOT NULL DEFAULT nextval('configuracion_empresa_id_seq'::regclass),
  nombre text NOT NULL DEFAULT 'TECNYCON CONSTRUCTORA'::text,
  rut text NOT NULL DEFAULT ''::text,
  direccion text NOT NULL DEFAULT ''::text,
  telefono text NOT NULL DEFAULT ''::text,
  email text NOT NULL DEFAULT ''::text,
  sitio_web text NOT NULL DEFAULT ''::text,
  logo text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_empresa_pkey PRIMARY KEY (id)
);
CREATE TABLE public.configuracion_seguridad (
  id bigint NOT NULL DEFAULT nextval('configuracion_seguridad_id_seq'::regclass),
  intentos_maximos integer NOT NULL DEFAULT 5,
  duracion_sesion integer NOT NULL DEFAULT 480,
  cambio_password_obligatorio boolean NOT NULL DEFAULT true,
  password_min_length integer NOT NULL DEFAULT 8,
  password_requiere_numero boolean NOT NULL DEFAULT true,
  password_requiere_mayuscula boolean NOT NULL DEFAULT true,
  password_requiere_especial boolean NOT NULL DEFAULT false,
  bloqueo_automatico boolean NOT NULL DEFAULT true,
  notificaciones_email boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_seguridad_pkey PRIMARY KEY (id)
);
CREATE TABLE public.configuracion_sistema (
  id bigint NOT NULL DEFAULT nextval('configuracion_sistema_id_seq'::regclass),
  modo_mantenimiento boolean NOT NULL DEFAULT false,
  backup_automatico boolean NOT NULL DEFAULT true,
  frecuencia_backup text NOT NULL DEFAULT 'diario'::text,
  retencion_logs integer NOT NULL DEFAULT 90,
  notificaciones_internas boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT configuracion_sistema_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contratos (
  id bigint NOT NULL DEFAULT nextval('contratos_id_seq'::regclass),
  trabajador_id bigint NOT NULL,
  obra_id bigint,
  numero_contrato text NOT NULL UNIQUE,
  es_anexo boolean DEFAULT false,
  contrato_padre_id bigint,
  tipo_anexo text,
  tipo_contrato text NOT NULL CHECK (tipo_contrato = ANY (ARRAY['indefinido'::text, 'plazo-fijo'::text])),
  fecha_inicio date NOT NULL,
  fecha_termino date,
  duracion_valor integer,
  duracion_unidad text CHECK (duracion_unidad = ANY (ARRAY['dias'::text, 'semanas'::text, 'meses'::text])),
  ciudad_contrato text NOT NULL,
  cargo text NOT NULL,
  funciones text,
  salario_base numeric NOT NULL,
  salario_palabras text NOT NULL,
  suple_quincenal numeric NOT NULL,
  suple_palabras text NOT NULL,
  jornada_tipo text DEFAULT 'estandar'::text CHECK (jornada_tipo = ANY (ARRAY['estandar'::text, 'especial'::text])),
  jornada_detalle text,
  afp text,
  prevision text,
  isapre text,
  pdf_url text,
  pdf_firmado_url text,
  estado_firma text DEFAULT 'pendiente'::text CHECK (estado_firma = ANY (ARRAY['pendiente'::text, 'firmado'::text])),
  fecha_firma date,
  generado_por bigint,
  fecha_generacion timestamp with time zone DEFAULT now(),
  activo boolean DEFAULT true,
  fecha_inactivacion timestamp with time zone,
  motivo_inactivacion text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contratos_pkey PRIMARY KEY (id),
  CONSTRAINT contratos_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT contratos_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id),
  CONSTRAINT contratos_contrato_padre_id_fkey FOREIGN KEY (contrato_padre_id) REFERENCES public.contratos(id),
  CONSTRAINT contratos_generado_por_fkey FOREIGN KEY (generado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.documentos_obligatorios_config (
  id integer NOT NULL DEFAULT nextval('documentos_obligatorios_config_id_seq'::regclass),
  nombre text NOT NULL UNIQUE,
  codigo text NOT NULL UNIQUE,
  categoria text NOT NULL CHECK (categoria = ANY (ARRAY['prevencion'::text, 'administrativo'::text])),
  descripcion text,
  tiene_vencimiento boolean DEFAULT false,
  dias_alerta_prevencimiento integer DEFAULT 30,
  requiere_firma boolean DEFAULT false,
  aplica_todas_categorias boolean DEFAULT true,
  categorias_trabajador ARRAY,
  activo boolean DEFAULT true,
  orden_visualizacion integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT documentos_obligatorios_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documentos_obra (
  id bigint NOT NULL DEFAULT nextval('documentos_obra_id_seq'::regclass),
  obra_id bigint NOT NULL,
  nombre text NOT NULL,
  tipo text,
  archivo text NOT NULL,
  fecha_subida timestamp with time zone DEFAULT now(),
  tamanio integer,
  descripcion text,
  subido_por bigint,
  CONSTRAINT documentos_obra_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_obra_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id),
  CONSTRAINT documentos_obra_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.documentos_trabajador (
  id bigint NOT NULL DEFAULT nextval('documentos_trabajador_id_seq'::regclass),
  trabajador_id bigint NOT NULL,
  nombre text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['contrato'::text, 'anexo_plazo'::text, 'anexo_obra'::text, 'finiquito'::text, 'odi'::text, 'odi_cargo'::text, 'cedula_identidad'::text, 'entrega_epp'::text, 'politica_acoso'::text, 'certificado_antecedentes'::text, 'entrega_ri'::text, 'politica_ad'::text, 'politica_sso'::text, 'datos_personales'::text, 'otro'::text])),
  categoria text CHECK (categoria = ANY (ARRAY['prevencion'::text, 'administrativo'::text])),
  obligatorio boolean DEFAULT false,
  estado_validacion text DEFAULT 'pendiente'::text CHECK (estado_validacion = ANY (ARRAY['pendiente'::text, 'vigente'::text, 'por_vencer'::text, 'vencido'::text, 'rechazado'::text])),
  fecha_vencimiento date,
  requiere_firma boolean DEFAULT false,
  firmado boolean DEFAULT false,
  fecha_firma date,
  archivo text,
  fecha_subida timestamp with time zone DEFAULT now(),
  tamanio integer,
  descripcion text,
  subido_por bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  obra_id integer,
  CONSTRAINT documentos_trabajador_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_trabajador_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT documentos_trabajador_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES public.usuarios(id),
  CONSTRAINT documentos_trabajador_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id)
);
CREATE TABLE public.evaluaciones (
  id bigint NOT NULL DEFAULT nextval('evaluaciones_id_seq'::regclass),
  trabajador_id bigint NOT NULL,
  fecha timestamp with time zone DEFAULT now(),
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['desempeño'::text, 'seguridad'::text, 'tecnica'::text])),
  puntaje integer NOT NULL CHECK (puntaje >= 1 AND puntaje <= 5),
  comentarios text,
  evaluador_id bigint,
  CONSTRAINT evaluaciones_pkey PRIMARY KEY (id),
  CONSTRAINT evaluaciones_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT evaluaciones_evaluador_id_fkey FOREIGN KEY (evaluador_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.finiquitos (
  id bigint NOT NULL DEFAULT nextval('finiquitos_id_seq'::regclass),
  contrato_id bigint NOT NULL,
  trabajador_id bigint NOT NULL,
  numero_finiquito text NOT NULL UNIQUE,
  fecha_finiquito date NOT NULL,
  causal_termino text NOT NULL,
  indemnizacion numeric DEFAULT 0,
  vacaciones_proporcionales numeric DEFAULT 0,
  otros_pagos numeric DEFAULT 0,
  total numeric NOT NULL,
  pdf_url text,
  pdf_firmado_url text,
  estado_firma text DEFAULT 'pendiente'::text CHECK (estado_firma = ANY (ARRAY['pendiente'::text, 'firmado'::text])),
  fecha_firma date,
  generado_por bigint,
  fecha_generacion timestamp with time zone DEFAULT now(),
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT finiquitos_pkey PRIMARY KEY (id),
  CONSTRAINT finiquitos_contrato_id_fkey FOREIGN KEY (contrato_id) REFERENCES public.contratos(id),
  CONSTRAINT finiquitos_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT finiquitos_generado_por_fkey FOREIGN KEY (generado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.gastos (
  id bigint NOT NULL DEFAULT nextval('gastos_id_seq'::regclass),
  obra_id bigint,
  fecha date NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['material'::text, 'mano-obra'::text, 'equipo'::text, 'subcontrato'::text, 'otro'::text])),
  categoria text,
  descripcion text NOT NULL,
  monto numeric NOT NULL,
  moneda text DEFAULT 'CLP'::text,
  proveedor text,
  documento text,
  registrado_por bigint,
  fecha_registro timestamp with time zone DEFAULT now(),
  CONSTRAINT gastos_pkey PRIMARY KEY (id),
  CONSTRAINT gastos_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id),
  CONSTRAINT gastos_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.historial_cambios (
  id bigint NOT NULL DEFAULT nextval('historial_cambios_id_seq'::regclass),
  trabajador_id bigint,
  fecha timestamp with time zone DEFAULT now(),
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['estado'::text, 'cargo'::text, 'salario'::text, 'obra'::text, 'contrato'::text, 'otro'::text])),
  campo text NOT NULL,
  valor_anterior text,
  valor_nuevo text NOT NULL,
  motivo text,
  realizado_por bigint,
  CONSTRAINT historial_cambios_pkey PRIMARY KEY (id),
  CONSTRAINT historial_cambios_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT historial_cambios_realizado_por_fkey FOREIGN KEY (realizado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.hitos (
  id bigint NOT NULL DEFAULT nextval('hitos_id_seq'::regclass),
  obra_id bigint NOT NULL,
  nombre text NOT NULL,
  descripcion text,
  fecha_estimada date NOT NULL,
  fecha_completado date,
  completado boolean DEFAULT false,
  progreso integer DEFAULT 0 CHECK (progreso >= 0 AND progreso <= 100),
  notas text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  CONSTRAINT hitos_pkey PRIMARY KEY (id),
  CONSTRAINT hitos_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id)
);
CREATE TABLE public.logs_auditoria (
  id bigint NOT NULL DEFAULT nextval('logs_auditoria_id_seq'::regclass),
  usuario_id bigint,
  fecha timestamp with time zone DEFAULT now(),
  accion text NOT NULL,
  modulo text NOT NULL,
  descripcion text,
  ip text,
  user_agent text,
  datos_adicionales jsonb,
  CONSTRAINT logs_auditoria_pkey PRIMARY KEY (id),
  CONSTRAINT logs_auditoria_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.materiales (
  id bigint NOT NULL DEFAULT nextval('materiales_id_seq'::regclass),
  obra_id bigint,
  nombre text NOT NULL,
  categoria text,
  unidad text NOT NULL,
  cantidad_estimada numeric,
  cantidad_utilizada numeric DEFAULT 0,
  costo_unitario numeric,
  moneda text DEFAULT 'CLP'::text,
  proveedor text,
  fecha_registro timestamp with time zone DEFAULT now(),
  registrado_por bigint,
  CONSTRAINT materiales_pkey PRIMARY KEY (id),
  CONSTRAINT materiales_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id),
  CONSTRAINT materiales_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.obras (
  id bigint NOT NULL DEFAULT nextval('obras_id_seq'::regclass),
  nombre text NOT NULL,
  codigo text UNIQUE,
  tipo text CHECK (tipo = ANY (ARRAY['construccion'::text, 'remodelacion'::text, 'mantenimiento'::text, 'otro'::text])),
  cliente text NOT NULL,
  rut_cliente text,
  direccion text NOT NULL,
  comuna text NOT NULL,
  region text NOT NULL,
  descripcion text,
  fecha_inicio date NOT NULL,
  fecha_termino_estimada date,
  fecha_termino_real date,
  monto_contrato numeric,
  moneda text DEFAULT 'CLP'::text,
  encargado_id bigint,
  estado text NOT NULL DEFAULT 'planificacion'::text CHECK (estado = ANY (ARRAY['planificacion'::text, 'en-progreso'::text, 'pausada'::text, 'terminada'::text, 'cancelada'::text])),
  progreso integer DEFAULT 0 CHECK (progreso >= 0 AND progreso <= 100),
  notas text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  ultima_actualizacion timestamp with time zone DEFAULT now(),
  CONSTRAINT obras_pkey PRIMARY KEY (id),
  CONSTRAINT obras_encargado_id_fkey FOREIGN KEY (encargado_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.solicitudes_acceso (
  id integer NOT NULL DEFAULT nextval('solicitudes_acceso_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  nombre character varying NOT NULL,
  auth_provider character varying NOT NULL,
  auth_user_id uuid,
  estado character varying NOT NULL DEFAULT 'pendiente'::character varying,
  rol_solicitado character varying,
  mensaje_solicitud text,
  mensaje_admin text,
  usuario_id integer,
  aprobada_por integer,
  fecha_solicitud timestamp with time zone DEFAULT now(),
  fecha_respuesta timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT solicitudes_acceso_pkey PRIMARY KEY (id),
  CONSTRAINT solicitudes_acceso_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT solicitudes_acceso_aprobada_por_fkey FOREIGN KEY (aprobada_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.trabajadores (
  id bigint NOT NULL DEFAULT nextval('trabajadores_id_seq'::regclass),
  nombre text NOT NULL,
  rut text NOT NULL UNIQUE,
  telefono text,
  direccion text,
  comuna text,
  region text,
  foto text,
  cargo text NOT NULL,
  fecha_ingreso date NOT NULL,
  salario text NOT NULL,
  tipo_contrato text CHECK (tipo_contrato = ANY (ARRAY['indefinido'::text, 'plazo-fijo'::text, 'obra'::text, 'honorarios'::text])),
  tipo_jornada text DEFAULT 'completa'::text CHECK (tipo_jornada = ANY (ARRAY['completa'::text, 'parcial'::text, 'turno'::text])),
  afp text,
  prevision text CHECK (prevision = ANY (ARRAY['fonasa'::text, 'isapre'::text])),
  isapre text,
  banco text,
  tipo_cuenta text CHECK (tipo_cuenta = ANY (ARRAY['corriente'::text, 'vista'::text, 'rut'::text])),
  numero_cuenta text,
  nacionalidad text CHECK (nacionalidad = ANY (ARRAY['chilena'::text, 'extranjera'::text])),
  estado_civil text CHECK (estado_civil = ANY (ARRAY['soltero'::text, 'casado'::text, 'viudo'::text, 'divorciado'::text])),
  estado text NOT NULL DEFAULT 'activo'::text CHECK (estado = ANY (ARRAY['activo'::text, 'vacaciones'::text, 'licencia'::text, 'retirado'::text])),
  notas text,
  fecha_creacion timestamp with time zone DEFAULT now(),
  ultima_actualizacion timestamp with time zone DEFAULT now(),
  asignacion_colacion numeric DEFAULT 0,
  asignacion_movilizacion numeric DEFAULT 0,
  CONSTRAINT trabajadores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trabajadores_obras (
  id bigint NOT NULL DEFAULT nextval('trabajadores_obras_id_seq'::regclass),
  trabajador_id bigint NOT NULL,
  obra_id bigint NOT NULL,
  cargo_en_obra text NOT NULL,
  fecha_asignacion timestamp with time zone DEFAULT now(),
  fecha_retiro timestamp with time zone,
  activo boolean DEFAULT true,
  CONSTRAINT trabajadores_obras_pkey PRIMARY KEY (id),
  CONSTRAINT trabajadores_obras_trabajador_id_fkey FOREIGN KEY (trabajador_id) REFERENCES public.trabajadores(id),
  CONSTRAINT trabajadores_obras_obra_id_fkey FOREIGN KEY (obra_id) REFERENCES public.obras(id)
);
CREATE TABLE public.usuarios (
  id bigint NOT NULL DEFAULT nextval('usuarios_id_seq'::regclass),
  nombre text NOT NULL,
  rut text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  telefono text,
  foto text,
  cargo text,
  fecha_ingreso date NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  rol text NOT NULL CHECK (rol = ANY (ARRAY['profesional'::text, 'visitador'::text, 'gerente'::text, 'super-admin'::text])),
  credenciales jsonb NOT NULL,
  permisos jsonb DEFAULT '{"obras": {"ver": true, "crear": false, "editar": false, "eliminar": false}, "finanzas": {"ver": false, "editar": false}, "reportes": {"ver": true, "generar": false}, "documentos": {"ver": true, "subir": false, "eliminar": false}, "trabajadores": {"ver": true, "crear": false, "editar": false, "eliminar": false}, "configuracion": {"ver": false, "editar": false}}'::jsonb,
  obras_asignadas ARRAY,
  fecha_creacion timestamp with time zone DEFAULT now(),
  ultima_actualizacion timestamp with time zone DEFAULT now(),
  CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);